In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
url = "https://www.worldometers.info/coronavirus/"

corona_content = requests.get(url, "html.parser")
soup = BeautifulSoup(corona_content.content)

In [3]:
table = soup.find("table", id="main_table_countries_today")

In [4]:
data = {
    "Country": [],
    "Total Cases": [],
    "New Cases": [],
    "Total Deaths": [],
    "New Deaths": [],
    "Total Recovered": [],
    "New Recovered": [],
    "Active Cases": [],
    "Serious, Critical": [],
    "Tot Cases/1M pop": [],
    "Deaths/1M pop": [],
    "Total tests": [],
    "Tests/1M pop": [],
    "Population": [],
    "Continent": [],
    "1 Case every X ppl": [],
    "1 Death every X ppl": [],
    "1 Test every X ppl": [],
    "New Cases/1M pop": [],
    "New Deaths/1M pop": [],
    "Active Cases/1M pop": [],
}

header_row = table.find("thead").find("tr")
data_rows = table.find("tbody").find_all("tr")

In [5]:
for row in data_rows[8:]:
    columns = row.find_all("td")[1:]
    for i, k in zip(columns, data):
        data[k].append(i.text.strip())

In [6]:
# Find the element containing the datetime string
date_elem = soup.find("div", class_="content-inner")

# Find the div element containing the datetime
date = date_elem.find("div", {"style": "font-size:13px; color:#999; margin-top:5px; text-align:center"})
content = date.text.strip()

# Split string so that we have a perfect datetime string
datetime = content[content.find('M'):content.find(', 1')].replace(',', '').replace(' ', '_')
print(datetime)

M

In [7]:
# Create a Pandas DataFrame from the dictionary
df = pd.DataFrame(data)

# Save the data to a CSV file
df.to_csv(f"{datetime}_corona_data.csv", index=False)

In [8]:
df.head()

,Country,Total Cases,New Cases,Total Deaths,New Deaths,Total Recovered,New Recovered,Active Cases,"Serious, Critical",Tot Cases/1M pop,...,Total tests,Tests/1M pop,Population,Continent,1 Case every X ppl,1 Death every X ppl,1 Test every X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,USA,"106,305,779",,"1,156,300",,"104,088,992",,"1,060,487","1,872","317,515",...,"1,175,014,579","3,509,546","334,805,269",North America,3,290,0,,,"3,167"
1,India,"44,739,054",,"530,929",,"44,182,538",,"25,587",N/A,"31,806",...,"922,164,863","655,584","1,406,631,776",Asia,31,"2,649",2,,,18
2,France,"39,817,657",,"165,794",,"39,517,588",,"134,275",869,"607,120",...,"271,490,188","4,139,547","65,584,518",Europe,2,396,0,,,"2,047"
3,Germany,"38,363,343",,"171,169",,"38,104,500",,"87,674",N/A,"457,340",...,"122,332,384","1,458,359","83,883,596",Europe,2,490,1,,,"1,045"
4,Brazil,"37,319,254",,"700,556",,"36,249,161",,"369,537",N/A,"173,293",...,"63,776,166","296,146","215,353,593",South America,6,307,3,,,"1,716"